// WC 2026 squads with pre-tournament top-10 flags based on club form / reputation
// isTop marks the standout players a casual fan should know about

const sq = (teamCode, players) =>
  players.map((p, i) => ({ id: `wc-${teamCode}-${i + 1}`, ...p }));

export const WC_SQUADS = {
  // ── POT 1 ──────────────────────────────────────────────────────────────────
  Argentina: sq('ARG', [
    { name: 'Emiliano Martínez', position: 'GK', isTop: true },
    { name: 'Geronimo Rulli', position: 'GK' },
    { name: 'Walter Benítez', position: 'GK' },
    { name: 'Nahuel Molina', position: 'DEF', isTop: true },
    { name: 'Gonzalo Montiel', position: 'DEF' },
    { name: 'Cristian Romero', position: 'DEF', isTop: true },
    { name: 'Lisandro Martínez', position: 'DEF', isTop: true },
    { name: 'Nicolás Otamendi', position: 'DEF' },
    { name: 'Germán Pezzella', position: 'DEF' },
    { name: 'Marcos Acuña', position: 'DEF' },
    { name: 'Nicolás Tagliafico', position: 'DEF' },
    { name: 'Alexis Mac Allister', position: 'MID', isTop: true },
    { name: 'Rodrigo De Paul', position: 'MID', isTop: true },
    { name: 'Enzo Fernández', position: 'MID', isTop: true },
    { name: 'Leandro Paredes', position: 'MID' },
    { name: 'Guido Rodríguez', position: 'MID' },
    { name: 'Giovani Lo Celso', position: 'MID' },
    { name: 'Lionel Messi', position: 'FWD', isTop: true },
    { name: 'Lautaro Martínez', position: 'FWD', isTop: true },
    { name: 'Julián Álvarez', position: 'FWD', isTop: true },
    { name: 'Paulo Dybala', position: 'FWD' },
    { name: 'Alejandro Garnacho', position: 'FWD' },
    { name: 'Ángel Di María', position: 'FWD' },
  ]),
  Brazil: sq('BRA', [
    { name: 'Alisson', position: 'GK', isTop: true },
    { name: 'Ederson', position: 'GK' },
    { name: 'Bento', position: 'GK' },
    { name: 'Danilo', position: 'DEF' },
    { name: 'Éder Militão', position: 'DEF', isTop: true },
    { name: 'Marquinhos', position: 'DEF', isTop: true },
    { name: 'Gabriel Magalhães', position: 'DEF', isTop: true },
    { name: 'Alex Sandro', position: 'DEF' },
    { name: 'Wendell', position: 'DEF' },
    { name: 'Vanderson', position: 'DEF' },
    { name: 'Casemiro', position: 'MID', isTop: true },
    { name: 'Lucas Paquetá', position: 'MID', isTop: true },
    { name: 'Gerson', position: 'MID' },
    { name: 'Bruno Guimarães', position: 'MID', isTop: true },
    { name: 'Andreas Pereira', position: 'MID' },
    { name: 'Vinicius Jr.', position: 'FWD', isTop: true },
    { name: 'Rodrygo', position: 'FWD', isTop: true },
    { name: 'Raphinha', position: 'FWD', isTop: true },
    { name: 'Endrick', position: 'FWD' },
    { name: 'Gabriel Martinelli', position: 'FWD' },
    { name: 'Richarlison', position: 'FWD' },
    { name: 'Gabriel Jesus', position: 'FWD' },
    { name: 'Savinho', position: 'FWD' },
  ]),
  France: sq('FRA', [
    { name: 'Mike Maignan', position: 'GK', isTop: true },
    { name: 'Alphonse Areola', position: 'GK' },
    { name: 'Brice Samba', position: 'GK' },
    { name: 'Jules Koundé', position: 'DEF', isTop: true },
    { name: 'Dayot Upamecano', position: 'DEF', isTop: true },
    { name: 'Ibrahima Konaté', position: 'DEF', isTop: true },
    { name: 'William Saliba', position: 'DEF', isTop: true },
    { name: 'Theo Hernandez', position: 'DEF', isTop: true },
    { name: 'Lucas Hernandez', position: 'DEF' },
    { name: 'Jonathan Clauss', position: 'DEF' },
    { name: "N'Golo Kanté", position: 'MID', isTop: true },
    { name: 'Aurélien Tchouaméni', position: 'MID', isTop: true },
    { name: 'Eduardo Camavinga', position: 'MID', isTop: true },
    { name: 'Adrien Rabiot', position: 'MID' },
    { name: 'Antoine Griezmann', position: 'MID' },
    { name: 'Kylian Mbappé', position: 'FWD', isTop: true },
    { name: 'Ousmane Dembélé', position: 'FWD', isTop: true },
    { name: 'Marcus Thuram', position: 'FWD' },
    { name: 'Kingsley Coman', position: 'FWD' },
    { name: 'Olivier Giroud', position: 'FWD' },
    { name: 'Randal Kolo Muani', position: 'FWD' },
    { name: 'Bradley Barcola', position: 'FWD' },
    { name: 'Mathys Tel', position: 'FWD' },
  ]),
  England: sq('ENG', [
    { name: 'Jordan Pickford', position: 'GK', isTop: true },
    { name: 'Aaron Ramsdale', position: 'GK' },
    { name: 'Dean Henderson', position: 'GK' },
    { name: 'Trent Alexander-Arnold', position: 'DEF', isTop: true },
    { name: 'Kyle Walker', position: 'DEF' },
    { name: 'Reece James', position: 'DEF', isTop: true },
    { name: 'John Stones', position: 'DEF', isTop: true },
    { name: 'Harry Maguire', position: 'DEF' },
    { name: 'Marc Guéhi', position: 'DEF', isTop: true },
    { name: 'Luke Shaw', position: 'DEF' },
    { name: 'Kieran Trippier', position: 'DEF' },
    { name: 'Declan Rice', position: 'MID', isTop: true },
    { name: 'Jude Bellingham', position: 'MID', isTop: true },
    { name: 'Kobbie Mainoo', position: 'MID', isTop: true },
    { name: 'Conor Gallagher', position: 'MID' },
    { name: 'Adam Wharton', position: 'MID' },
    { name: 'Harry Kane', position: 'FWD', isTop: true },
    { name: 'Bukayo Saka', position: 'FWD', isTop: true },
    { name: 'Phil Foden', position: 'FWD', isTop: true },
    { name: 'Marcus Rashford', position: 'FWD' },
    { name: 'Jarrod Bowen', position: 'FWD' },
    { name: 'Anthony Gordon', position: 'FWD' },
    { name: 'Ollie Watkins', position: 'FWD' },
  ]),
  Spain: sq('ESP', [
    { name: 'Unai Simón', position: 'GK', isTop: true },
    { name: 'David Raya', position: 'GK' },
    { name: 'Alex Remiro', position: 'GK' },
    { name: 'Dani Carvajal', position: 'DEF', isTop: true },
    { name: 'Aymeric Laporte', position: 'DEF' },
    { name: 'Robin Le Normand', position: 'DEF', isTop: true },
    { name: 'Pau Cubarsí', position: 'DEF', isTop: true },
    { name: 'Marc Cucurella', position: 'DEF', isTop: true },
    { name: 'Alejandro Grimaldo', position: 'DEF', isTop: true },
    { name: 'Pedro Porro', position: 'DEF' },
    { name: 'Pedri', position: 'MID', isTop: true },
    { name: 'Gavi', position: 'MID', isTop: true },
    { name: 'Rodri', position: 'MID', isTop: true },
    { name: 'Dani Olmo', position: 'MID', isTop: true },
    { name: 'Martín Zubimendi', position: 'MID' },
    { name: 'Fabian Ruiz', position: 'MID' },
    { name: 'Lamine Yamal', position: 'FWD', isTop: true },
    { name: 'Nico Williams', position: 'FWD', isTop: true },
    { name: 'Álvaro Morata', position: 'FWD' },
    { name: 'Mikel Oyarzabal', position: 'FWD' },
    { name: 'Ferran Torres', position: 'FWD' },
    { name: 'Bryan Gil', position: 'FWD' },
    { name: 'Ayoze Pérez', position: 'FWD' },
  ]),
  Portugal: sq('POR', [
    { name: 'Diogo Costa', position: 'GK', isTop: true },
    { name: 'Rui Patrício', position: 'GK' },
    { name: 'José Sá', position: 'GK' },
    { name: 'João Cancelo', position: 'DEF', isTop: true },
    { name: 'Nuno Mendes', position: 'DEF', isTop: true },
    { name: 'Rúben Dias', position: 'DEF', isTop: true },
    { name: 'Pepe', position: 'DEF' },
    { name: 'António Silva', position: 'DEF', isTop: true },
    { name: 'Diogo Dalot', position: 'DEF' },
    { name: 'Nélson Semedo', position: 'DEF' },
    { name: 'Bruno Fernandes', position: 'MID', isTop: true },
    { name: 'Bernardo Silva', position: 'MID', isTop: true },
    { name: 'João Palhinha', position: 'MID', isTop: true },
    { name: 'Vitinha', position: 'MID', isTop: true },
    { name: 'Rúben Neves', position: 'MID' },
    { name: 'Matheus Nunes', position: 'MID' },
    { name: 'Cristiano Ronaldo', position: 'FWD', isTop: true },
    { name: 'Rafael Leão', position: 'FWD', isTop: true },
    { name: 'Pedro Neto', position: 'FWD', isTop: true },
    { name: 'Gonçalo Ramos', position: 'FWD' },
    { name: 'Francisco Conceição', position: 'FWD' },
    { name: 'João Félix', position: 'FWD' },
    { name: 'Diogo Jota', position: 'FWD' },
  ]),
  Netherlands: sq('NED', [
    { name: 'Mark Flekken', position: 'GK' },
    { name: 'Bart Verbruggen', position: 'GK', isTop: true },
    { name: 'Remko Pasveer', position: 'GK' },
    { name: 'Denzel Dumfries', position: 'DEF', isTop: true },
    { name: 'Virgil van Dijk', position: 'DEF', isTop: true },
    { name: 'Stefan de Vrij', position: 'DEF', isTop: true },
    { name: 'Nathan Aké', position: 'DEF', isTop: true },
    { name: 'Jurrien Timber', position: 'DEF', isTop: true },
    { name: 'Matthijs de Ligt', position: 'DEF' },
    { name: 'Daley Blind', position: 'DEF' },
    { name: 'Frenkie de Jong', position: 'MID', isTop: true },
    { name: 'Tijjani Reijnders', position: 'MID', isTop: true },
    { name: 'Teun Koopmeiners', position: 'MID', isTop: true },
    { name: 'Ryan Gravenberch', position: 'MID', isTop: true },
    { name: 'Xavi Simons', position: 'MID', isTop: true },
    { name: 'Memphis Depay', position: 'FWD' },
    { name: 'Cody Gakpo', position: 'FWD', isTop: true },
    { name: 'Wout Weghorst', position: 'FWD' },
    { name: 'Donyell Malen', position: 'FWD' },
    { name: 'Steven Bergwijn', position: 'FWD' },
    { name: 'Brian Brobbey', position: 'FWD' },
    { name: 'Noa Lang', position: 'FWD' },
  ]),
  Germany: sq('GER', [
    { name: 'Manuel Neuer', position: 'GK', isTop: true },
    { name: 'Marc-André ter Stegen', position: 'GK' },
    { name: 'Oliver Baumann', position: 'GK' },
    { name: 'Joshua Kimmich', position: 'DEF', isTop: true },
    { name: 'Antonio Rüdiger', position: 'DEF', isTop: true },
    { name: 'Jonathan Tah', position: 'DEF', isTop: true },
    { name: 'Nico Schlotterbeck', position: 'DEF', isTop: true },
    { name: 'Maximilian Mittelstädt', position: 'DEF' },
    { name: 'David Raum', position: 'DEF' },
    { name: 'Waldemar Anton', position: 'DEF' },
    { name: 'Toni Kroos', position: 'MID', isTop: true },
    { name: 'Ilkay Gündogan', position: 'MID', isTop: true },
    { name: 'Robert Andrich', position: 'MID' },
    { name: 'Pascal Groß', position: 'MID' },
    { name: 'Florian Wirtz', position: 'MID', isTop: true },
    { name: 'Jamal Musiala', position: 'FWD', isTop: true },
    { name: 'Leroy Sané', position: 'FWD', isTop: true },
    { name: 'Serge Gnabry', position: 'FWD' },
    { name: 'Thomas Müller', position: 'FWD' },
    { name: 'Kai Havertz', position: 'FWD', isTop: true },
    { name: 'Niclas Füllkrug', position: 'FWD', isTop: true },
    { name: 'Deniz Undav', position: 'FWD' },
    { name: 'Tim Kleindienst', position: 'FWD' },
  ]),
  Belgium: sq('BEL', [
    { name: 'Koen Casteels', position: 'GK', isTop: true },
    { name: 'Thomas Kaminski', position: 'GK' },
    { name: 'Matz Sels', position: 'GK' },
    { name: 'Thomas Castagne', position: 'DEF', isTop: true },
    { name: 'Toby Alderweireld', position: 'DEF' },
    { name: 'Jan Vertonghen', position: 'DEF' },
    { name: 'Wout Faes', position: 'DEF', isTop: true },
    { name: 'Arthur Theate', position: 'DEF', isTop: true },
    { name: 'Zeno Debast', position: 'DEF', isTop: true },
    { name: 'Axel Witsel', position: 'MID' },
    { name: 'Kevin De Bruyne', position: 'MID', isTop: true },
    { name: 'Youri Tielemans', position: 'MID', isTop: true },
    { name: 'Amadou Onana', position: 'MID', isTop: true },
    { name: 'Orel Mangala', position: 'MID' },
    { name: 'Romelu Lukaku', position: 'FWD', isTop: true },
    { name: 'Dries Mertens', position: 'FWD' },
    { name: 'Leandro Trossard', position: 'FWD', isTop: true },
    { name: 'Jeremy Doku', position: 'FWD', isTop: true },
    { name: 'Charles De Ketelaere', position: 'FWD', isTop: true },
    { name: 'Lois Openda', position: 'FWD', isTop: true },
    { name: 'Johan Bakayoko', position: 'FWD' },
  ]),
  Canada: sq('CAN', [
    { name: 'Maxime Crépeau', position: 'GK', isTop: true },
    { name: 'Milan Borjan', position: 'GK' },
    { name: 'James Pantemis', position: 'GK' },
    { name: 'Alistair Johnston', position: 'DEF', isTop: true },
    { name: 'Richie Laryea', position: 'DEF' },
    { name: 'Steven Vitória', position: 'DEF' },
    { name: 'Kamal Miller', position: 'DEF', isTop: true },
    { name: 'Doneil Henry', position: 'DEF' },
    { name: 'Sam Adekugbe', position: 'DEF' },
    { name: 'Derek Cornelius', position: 'DEF' },
    { name: 'Atiba Hutchinson', position: 'MID' },
    { name: 'Stephen Eustáquio', position: 'MID', isTop: true },
    { name: 'Ismaël Koné', position: 'MID', isTop: true },
    { name: 'Samuel Piette', position: 'MID' },
    { name: 'Jonathan Osorio', position: 'MID', isTop: true },
    { name: 'Alphonso Davies', position: 'FWD', isTop: true },
    { name: 'Jonathan David', position: 'FWD', isTop: true },
    { name: 'Tajon Buchanan', position: 'FWD', isTop: true },
    { name: 'Junior Hoilett', position: 'FWD' },
    { name: 'Cyle Larin', position: 'FWD', isTop: true },
    { name: 'Lucas Cavallini', position: 'FWD' },
    { name: 'Theo Bair', position: 'FWD' },
  ]),
  Mexico: sq('MEX', [
    { name: 'Guillermo Ochoa', position: 'GK', isTop: true },
    { name: 'Rodolfo Cota', position: 'GK' },
    { name: 'Luis Malagón', position: 'GK' },
    { name: 'Julián Araujo', position: 'DEF', isTop: true },
    { name: 'Jorge Sánchez', position: 'DEF' },
    { name: 'César Montes', position: 'DEF', isTop: true },
    { name: 'Héctor Moreno', position: 'DEF' },
    { name: 'Johan Vásquez', position: 'DEF', isTop: true },
    { name: 'Gerardo Arteaga', position: 'DEF' },
    { name: 'Jesús Gallardo', position: 'DEF' },
    { name: 'Edson Álvarez', position: 'MID', isTop: true },
    { name: 'Héctor Herrera', position: 'MID' },
    { name: 'Luis Romo', position: 'MID', isTop: true },
    { name: 'Carlos Rodríguez', position: 'MID', isTop: true },
    { name: 'Orbelín Pineda', position: 'MID', isTop: true },
    { name: 'Hirving Lozano', position: 'FWD', isTop: true },
    { name: 'Alexis Vega', position: 'FWD' },
    { name: 'Roberto Alvarado', position: 'FWD' },
    { name: 'Raúl Jiménez', position: 'FWD', isTop: true },
    { name: 'Santiago Giménez', position: 'FWD', isTop: true },
    { name: 'Henry Martín', position: 'FWD', isTop: true },
    { name: 'Uriel Antuna', position: 'FWD' },
  ]),
  USA: sq('USA', [
    { name: 'Matt Turner', position: 'GK', isTop: true },
    { name: 'Ethan Horvath', position: 'GK' },
    { name: 'Patrick Schulte', position: 'GK' },
    { name: 'Antonee Robinson', position: 'DEF', isTop: true },
    { name: 'Sergiño Dest', position: 'DEF', isTop: true },
    { name: 'Chris Richards', position: 'DEF', isTop: true },
    { name: 'Tim Ream', position: 'DEF' },
    { name: 'Miles Robinson', position: 'DEF', isTop: true },
    { name: 'Walker Zimmermann', position: 'DEF' },
    { name: 'DeAndre Yedlin', position: 'DEF' },
    { name: 'Tyler Adams', position: 'MID', isTop: true },
    { name: 'Weston McKennie', position: 'MID', isTop: true },
    { name: 'Yunus Musah', position: 'MID', isTop: true },
    { name: 'Gio Reyna', position: 'MID', isTop: true },
    { name: 'Brenden Aaronson', position: 'MID' },
    { name: 'Christian Pulisic', position: 'FWD', isTop: true },
    { name: 'Timothy Weah', position: 'FWD', isTop: true },
    { name: 'Folarin Balogun', position: 'FWD', isTop: true },
    { name: 'Josh Sargent', position: 'FWD' },
    { name: 'Jordan Morris', position: 'FWD' },
    { name: 'Ricardo Pepi', position: 'FWD' },
    { name: 'Malik Tillman', position: 'FWD' },
  ]),

  // ── POT 2 ──────────────────────────────────────────────────────────────────
  Croatia: sq('CRO', [
    { name: 'Dominik Livaković', position: 'GK', isTop: true },
    { name: 'Ivo Grbić', position: 'GK' },
    { name: 'Nediljko Labrović', position: 'GK' },
    { name: 'Josip Juranović', position: 'DEF', isTop: true },
    { name: 'Borna Sosa', position: 'DEF', isTop: true },
    { name: 'Joško Gvardiol', position: 'DEF', isTop: true },
    { name: 'Duje Ćaleta-Car', position: 'DEF', isTop: true },
    { name: 'Martin Erlić', position: 'DEF' },
    { name: 'Borna Barišić', position: 'DEF' },
    { name: 'Šime Vrsaljko', position: 'DEF' },
    { name: 'Luka Modrić', position: 'MID', isTop: true },
    { name: 'Mateo Kovačić', position: 'MID', isTop: true },
    { name: 'Marcelo Brozović', position: 'MID', isTop: true },
    { name: 'Mario Pašalić', position: 'MID', isTop: true },
    { name: 'Lovro Majer', position: 'MID', isTop: true },
    { name: 'Ivan Perišić', position: 'FWD', isTop: true },
    { name: 'Ante Budimir', position: 'FWD', isTop: true },
    { name: 'Andrej Kramarić', position: 'FWD', isTop: true },
    { name: 'Bruno Petković', position: 'FWD' },
    { name: 'Marko Livaja', position: 'FWD' },
    { name: 'Luka Ivanušec', position: 'FWD' },
    { name: 'Dario Špikić', position: 'FWD' },
  ]),
  Morocco: sq('MAR', [
    { name: 'Yassine Bounou', position: 'GK', isTop: true },
    { name: 'Munir Mohamedi', position: 'GK' },
    { name: 'Anas Zniti', position: 'GK' },
    { name: 'Achraf Hakimi', position: 'DEF', isTop: true },
    { name: 'Noussair Mazraoui', position: 'DEF', isTop: true },
    { name: 'Romain Saïss', position: 'DEF', isTop: true },
    { name: 'Nayef Aguerd', position: 'DEF', isTop: true },
    { name: 'Yahya Attiyat-Allah', position: 'DEF', isTop: true },
    { name: 'Badr Benoun', position: 'DEF' },
    { name: 'Jawad El Yamiq', position: 'DEF' },
    { name: 'Sofyan Amrabat', position: 'MID', isTop: true },
    { name: 'Azzedine Ounahi', position: 'MID', isTop: true },
    { name: 'Selim Amallah', position: 'MID' },
    { name: 'Bilal El Khannouss', position: 'MID', isTop: true },
    { name: 'Ilias Chair', position: 'MID' },
    { name: 'Hakim Ziyech', position: 'FWD', isTop: true },
    { name: 'Youssef En-Nesyri', position: 'FWD', isTop: true },
    { name: 'Abde Ezzalzouli', position: 'FWD' },
    { name: 'Soufiane Rahimi', position: 'FWD' },
    { name: 'Ayoub El Kaabi', position: 'FWD', isTop: true },
    { name: 'Anass Zaroury', position: 'FWD' },
  ]),
  Colombia: sq('COL', [
    { name: 'Camilo Vargas', position: 'GK', isTop: true },
    { name: 'David Ospina', position: 'GK' },
    { name: 'Álvaro Montero', position: 'GK' },
    { name: 'Santiago Arias', position: 'DEF' },
    { name: 'Daniel Muñoz', position: 'DEF', isTop: true },
    { name: 'Yerry Mina', position: 'DEF', isTop: true },
    { name: 'Davinson Sánchez', position: 'DEF', isTop: true },
    { name: 'Carlos Cuesta', position: 'DEF', isTop: true },
    { name: 'Johan Mojica', position: 'DEF', isTop: true },
    { name: 'William Tesillo', position: 'DEF' },
    { name: 'Wilmar Barrios', position: 'MID', isTop: true },
    { name: 'Mateus Uribe', position: 'MID' },
    { name: 'Jefferson Lerma', position: 'MID', isTop: true },
    { name: 'Juan Cuadrado', position: 'MID' },
    { name: 'James Rodríguez', position: 'MID', isTop: true },
    { name: 'Luis Díaz', position: 'FWD', isTop: true },
    { name: 'Rafael Santos Borré', position: 'FWD' },
    { name: 'Jhon Córdoba', position: 'FWD' },
    { name: 'Cucho Hernández', position: 'FWD', isTop: true },
    { name: 'Yerson Mosquera', position: 'DEF' },
    { name: 'Alfredo Morelos', position: 'FWD' },
    { name: 'Jhon Jáder Durán', position: 'FWD', isTop: true },
  ]),
  Uruguay: sq('URU', [
    { name: 'Sergio Rochet', position: 'GK', isTop: true },
    { name: 'Fernando Muslera', position: 'GK' },
    { name: 'Sebastián Sosa', position: 'GK' },
    { name: 'Nahitan Nández', position: 'DEF', isTop: true },
    { name: 'José María Giménez', position: 'DEF', isTop: true },
    { name: 'Sebastián Cáceres', position: 'DEF' },
    { name: 'Ronald Araújo', position: 'DEF', isTop: true },
    { name: 'Mathías Olivera', position: 'DEF', isTop: true },
    { name: 'Martín Cáceres', position: 'DEF' },
    { name: 'Marcelo Saracchi', position: 'DEF' },
    { name: 'Rodrigo Bentancur', position: 'MID', isTop: true },
    { name: 'Matías Vecino', position: 'MID' },
    { name: 'Federico Valverde', position: 'MID', isTop: true },
    { name: 'Facundo Pellistri', position: 'MID', isTop: true },
    { name: 'Gastón Pereiro', position: 'MID' },
    { name: 'Darwin Núñez', position: 'FWD', isTop: true },
    { name: 'Edinson Cavani', position: 'FWD', isTop: true },
    { name: 'Luis Suárez', position: 'FWD', isTop: true },
    { name: 'Maximiliano Gómez', position: 'FWD' },
    { name: 'Maxi Araújo', position: 'FWD' },
    { name: 'Agustín Canobbio', position: 'FWD', isTop: true },
    { name: 'Brian Rodríguez', position: 'FWD' },
  ]),
  Switzerland: sq('SUI', [
    { name: 'Yann Sommer', position: 'GK', isTop: true },
    { name: 'Gregor Kobel', position: 'GK', isTop: true },
    { name: 'Jonas Omlin', position: 'GK' },
    { name: 'Silvan Widmer', position: 'DEF', isTop: true },
    { name: 'Kevin Mbabu', position: 'DEF' },
    { name: 'Manuel Akanji', position: 'DEF', isTop: true },
    { name: 'Nico Elvedi', position: 'DEF', isTop: true },
    { name: 'Ricardo Rodríguez', position: 'DEF', isTop: true },
    { name: 'Fabian Schär', position: 'DEF', isTop: true },
    { name: 'Edimilson Fernandes', position: 'DEF' },
    { name: 'Granit Xhaka', position: 'MID', isTop: true },
    { name: 'Remo Freuler', position: 'MID', isTop: true },
    { name: 'Denis Zakaria', position: 'MID', isTop: true },
    { name: 'Renato Steffen', position: 'MID' },
    { name: 'Michel Aebischer', position: 'MID' },
    { name: 'Xherdan Shaqiri', position: 'FWD', isTop: true },
    { name: 'Breel Embolo', position: 'FWD', isTop: true },
    { name: 'Haris Seferović', position: 'FWD' },
    { name: 'Noah Okafor', position: 'FWD', isTop: true },
    { name: 'Kwadwo Duah', position: 'FWD' },
    { name: 'Dan Ndoye', position: 'FWD' },
    { name: 'Zeki Amdouni', position: 'FWD' },
  ]),
  Japan: sq('JPN', [
    { name: 'Shuichi Gonda', position: 'GK', isTop: true },
    { name: 'Zion Suzuki', position: 'GK' },
    { name: 'Kosei Tani', position: 'GK' },
    { name: 'Hiroki Sakai', position: 'DEF' },
    { name: 'Yuto Nagatomo', position: 'DEF' },
    { name: 'Maya Yoshida', position: 'DEF', isTop: true },
    { name: 'Ko Itakura', position: 'DEF', isTop: true },
    { name: 'Shogo Taniguchi', position: 'DEF' },
    { name: 'Miki Yamane', position: 'DEF' },
    { name: 'Takehiro Tomiyasu', position: 'DEF', isTop: true },
    { name: 'Gaku Shibasaki', position: 'MID' },
    { name: 'Wataru Endo', position: 'MID', isTop: true },
    { name: 'Hidemasa Morita', position: 'MID', isTop: true },
    { name: 'Ao Tanaka', position: 'MID', isTop: true },
    { name: 'Junya Ito', position: 'FWD', isTop: true },
    { name: 'Takumi Minamino', position: 'FWD', isTop: true },
    { name: 'Kaoru Mitoma', position: 'FWD', isTop: true },
    { name: 'Ritsu Doan', position: 'FWD', isTop: true },
    { name: 'Kyogo Furuhashi', position: 'FWD', isTop: true },
    { name: 'Daichi Kamada', position: 'MID', isTop: true },
    { name: 'Ayase Ueda', position: 'FWD' },
    { name: 'Takefusa Kubo', position: 'FWD', isTop: true },
  ]),
  Senegal: sq('SEN', [
    { name: 'Édouard Mendy', position: 'GK', isTop: true },
    { name: 'Alfred Gomis', position: 'GK' },
    { name: 'Seny Dieng', position: 'GK' },
    { name: 'Bouna Sarr', position: 'DEF' },
    { name: 'Youssouf Sabaly', position: 'DEF', isTop: true },
    { name: 'Kalidou Koulibaly', position: 'DEF', isTop: true },
    { name: 'Abdou Diallo', position: 'DEF', isTop: true },
    { name: 'Formose Mendy', position: 'DEF' },
    { name: 'Fodé Ballo-Touré', position: 'DEF', isTop: true },
    { name: 'Moussa Ndiaye', position: 'DEF' },
    { name: 'Cheikhou Kouyaté', position: 'MID' },
    { name: 'Idrissa Gana Gueye', position: 'MID', isTop: true },
    { name: 'Nampalys Mendy', position: 'MID' },
    { name: 'Pape Gueye', position: 'MID', isTop: true },
    { name: 'Lamine Camara', position: 'MID', isTop: true },
    { name: 'Sadio Mané', position: 'FWD', isTop: true },
    { name: 'Ismaïla Sarr', position: 'FWD', isTop: true },
    { name: 'Habib Diallo', position: 'FWD' },
    { name: 'Boulaye Dia', position: 'FWD', isTop: true },
    { name: 'Nicolas Jackson', position: 'FWD', isTop: true },
    { name: 'Iliman Ndiaye', position: 'FWD', isTop: true },
    { name: 'Famara Diédhiou', position: 'FWD' },
  ]),
  Iran: sq('IRN', [
    { name: 'Alireza Beiranvand', position: 'GK', isTop: true },
    { name: 'Hossein Hosseini', position: 'GK' },
    { name: 'Payam Niazmand', position: 'GK' },
    { name: 'Sadegh Moharrami', position: 'DEF', isTop: true },
    { name: 'Ramin Rezaeian', position: 'DEF', isTop: true },
    { name: 'Majid Hosseini', position: 'DEF', isTop: true },
    { name: 'Morteza Pouraliganji', position: 'DEF', isTop: true },
    { name: 'Shojae Khalilzadeh', position: 'DEF', isTop: true },
    { name: 'Mohammad Mohammadi', position: 'DEF' },
    { name: 'Abolfazl Jalali', position: 'DEF' },
    { name: 'Saeid Ezatolahi', position: 'MID', isTop: true },
    { name: 'Ahmad Nourollahi', position: 'MID', isTop: true },
    { name: 'Ali Gholizadeh', position: 'MID', isTop: true },
    { name: 'Alireza Jahanbakhsh', position: 'FWD', isTop: true },
    { name: 'Sardar Azmoun', position: 'FWD', isTop: true },
    { name: 'Mehdi Taremi', position: 'FWD', isTop: true },
    { name: 'Karim Ansarifard', position: 'FWD' },
    { name: 'Saman Ghoddos', position: 'FWD' },
    { name: 'Milad Mohammadi', position: 'DEF' },
    { name: 'Ali Karimi', position: 'MID' },
    { name: 'Omid Nourafkan', position: 'MID' },
    { name: 'Allahyar Sayyadmanesh', position: 'FWD' },
  ]),
  'South Korea': sq('KOR', [
    { name: 'Kim Seung-gyu', position: 'GK', isTop: true },
    { name: 'Song Bum-keun', position: 'GK' },
    { name: 'Jo Hyeon-woo', position: 'GK' },
    { name: 'Kim Tae-hwan', position: 'DEF' },
    { name: 'Lee Yong', position: 'DEF' },
    { name: 'Kim Min-jae', position: 'DEF', isTop: true },
    { name: 'Kim Young-gwon', position: 'DEF' },
    { name: 'Lee Ki-je', position: 'DEF' },
    { name: 'Hong Chul', position: 'DEF' },
    { name: 'Yoon Jong-gyu', position: 'DEF' },
    { name: 'Jung Woo-young', position: 'MID', isTop: true },
    { name: 'Hwang In-beom', position: 'MID', isTop: true },
    { name: 'Son Heung-min', position: 'FWD', isTop: true },
    { name: 'Lee Kang-in', position: 'FWD', isTop: true },
    { name: 'Hwang Hee-chan', position: 'FWD', isTop: true },
    { name: 'Cho Gue-sung', position: 'FWD', isTop: true },
    { name: 'Jeong Woo-yeong', position: 'MID', isTop: true },
    { name: 'Kim Jin-su', position: 'DEF', isTop: true },
    { name: 'Bae Jun-ho', position: 'MID', isTop: true },
    { name: 'Lee Jae-sung', position: 'MID', isTop: true },
    { name: 'Oh Hyeon-gyu', position: 'FWD' },
    { name: 'Yang Hyun-jun', position: 'FWD' },
  ]),
  Ecuador: sq('ECU', [
    { name: 'Hernán Galíndez', position: 'GK', isTop: true },
    { name: 'Alexander Domínguez', position: 'GK' },
    { name: 'Moisés Ramírez', position: 'GK' },
    { name: 'Angelo Preciado', position: 'DEF', isTop: true },
    { name: 'Pervis Estupiñán', position: 'DEF', isTop: true },
    { name: 'Robert Arboleda', position: 'DEF', isTop: true },
    { name: 'Félix Torres', position: 'DEF', isTop: true },
    { name: 'Piero Hincapié', position: 'DEF', isTop: true },
    { name: 'Byron Castillo', position: 'DEF' },
    { name: 'Jackson Porozo', position: 'DEF' },
    { name: 'Carlos Gruezo', position: 'MID' },
    { name: 'Jhegson Méndez', position: 'MID' },
    { name: 'Alan Franco', position: 'MID' },
    { name: 'Moisés Caicedo', position: 'MID', isTop: true },
    { name: 'Jeremy Sarmiento', position: 'MID', isTop: true },
    { name: 'Enner Valencia', position: 'FWD', isTop: true },
    { name: 'Gonzalo Plata', position: 'FWD', isTop: true },
    { name: 'Djorkaeff Reasco', position: 'FWD' },
    { name: 'Michael Estrada', position: 'FWD', isTop: true },
    { name: 'Kevin Rodríguez', position: 'FWD' },
    { name: 'Ángel Mena', position: 'FWD' },
    { name: 'Jordy Caicedo', position: 'FWD' },
  ]),
  Austria: sq('AUT', [
    { name: 'Patrick Pentz', position: 'GK', isTop: true },
    { name: 'Alexander Schlager', position: 'GK' },
    { name: 'Heinz Lindner', position: 'GK' },
    { name: 'Stefan Lainer', position: 'DEF' },
    { name: 'Philipp Lienhart', position: 'DEF', isTop: true },
    { name: 'Kevin Danso', position: 'DEF', isTop: true },
    { name: 'Maximilian Wöber', position: 'DEF', isTop: true },
    { name: 'David Alaba', position: 'DEF', isTop: true },
    { name: 'Phillipp Mwene', position: 'DEF' },
    { name: 'Gernot Trauner', position: 'DEF', isTop: true },
    { name: 'Nicolas Seiwald', position: 'MID', isTop: true },
    { name: 'Florian Grillitsch', position: 'MID' },
    { name: 'Konrad Laimer', position: 'MID', isTop: true },
    { name: 'Marcel Sabitzer', position: 'MID', isTop: true },
    { name: 'Christoph Baumgartner', position: 'MID', isTop: true },
    { name: 'Marko Arnautovic', position: 'FWD', isTop: true },
    { name: 'Michael Gregoritsch', position: 'FWD', isTop: true },
    { name: 'Patrick Wimmer', position: 'FWD' },
    { name: 'Florian Kainz', position: 'FWD' },
    { name: 'Andreas Weimann', position: 'FWD' },
    { name: 'Romano Schmid', position: 'MID' },
    { name: 'Guido Burgstaller', position: 'FWD' },
  ]),
  Australia: sq('AUS', [
    { name: 'Mathew Ryan', position: 'GK', isTop: true },
    { name: 'Danny Vukovic', position: 'GK' },
    { name: 'Andrew Redmayne', position: 'GK' },
    { name: 'Miloš Degenek', position: 'DEF', isTop: true },
    { name: 'Bailey Wright', position: 'DEF' },
    { name: 'Harry Souttar', position: 'DEF', isTop: true },
    { name: 'Kye Rowles', position: 'DEF', isTop: true },
    { name: 'Nathaniel Atkinson', position: 'DEF', isTop: true },
    { name: 'Aziz Behich', position: 'DEF' },
    { name: 'Joel King', position: 'DEF' },
    { name: 'Aaron Mooy', position: 'MID', isTop: true },
    { name: 'Jackson Irvine', position: 'MID', isTop: true },
    { name: 'Riley McGree', position: 'MID', isTop: true },
    { name: 'Cameron Devlin', position: 'MID' },
    { name: 'Keanu Baccus', position: 'MID' },
    { name: 'Mat Leckie', position: 'FWD', isTop: true },
    { name: 'Martin Boyle', position: 'FWD', isTop: true },
    { name: 'Mitchell Duke', position: 'FWD', isTop: true },
    { name: 'Jamie Maclaren', position: 'FWD', isTop: true },
    { name: 'Craig Goodwin', position: 'FWD', isTop: true },
    { name: 'Jason Cummings', position: 'FWD' },
    { name: 'Garang Kuol', position: 'FWD' },
  ]),

  // ── POT 3 ──────────────────────────────────────────────────────────────────
  Norway: sq('NOR', [
    { name: 'Ørjan Nyland', position: 'GK', isTop: true },
    { name: 'Rune Jarstein', position: 'GK' },
    { name: 'Kristoffer Klaesson', position: 'GK' },
    { name: 'Omar Elabdellaoui', position: 'DEF', isTop: true },
    { name: 'Kristoffer Ajer', position: 'DEF', isTop: true },
    { name: 'Andreas Hanche-Olsen', position: 'DEF' },
    { name: 'Stian Gregersen', position: 'DEF' },
    { name: 'Birger Meling', position: 'DEF' },
    { name: 'Fredrik Myrvold', position: 'DEF' },
    { name: 'Leo Skiri Østigård', position: 'DEF', isTop: true },
    { name: 'Sander Berge', position: 'MID', isTop: true },
    { name: 'Mats Møller Dæhli', position: 'MID' },
    { name: 'Fredrik Aursnes', position: 'MID', isTop: true },
    { name: 'Martin Ødegaard', position: 'MID', isTop: true },
    { name: 'Elias Kristoffersen', position: 'MID' },
    { name: 'Erling Haaland', position: 'FWD', isTop: true },
    { name: 'Alexander Sørloth', position: 'FWD', isTop: true },
    { name: 'Mohamed Elyounoussi', position: 'FWD', isTop: true },
    { name: 'Ola Solbakken', position: 'FWD' },
    { name: 'Antonio Nusa', position: 'FWD', isTop: true },
    { name: 'Jørgen Strand Larsen', position: 'FWD', isTop: true },
    { name: 'Hakon Evjen', position: 'FWD' },
  ]),
  Panama: sq('PAN', [
    { name: 'Luis Mejía', position: 'GK', isTop: true },
    { name: 'Orlando Mosquera', position: 'GK' },
    { name: 'Gianluca Busio', position: 'MID', isTop: true },
    { name: 'Fidel Escobar', position: 'DEF', isTop: true },
    { name: 'Eric Davis', position: 'DEF', isTop: true },
    { name: 'Andrés Andrade', position: 'MID', isTop: true },
    { name: 'César Yanis', position: 'MID' },
    { name: 'Édgar Bárcenas', position: 'FWD', isTop: true },
    { name: 'Aníbal Godoy', position: 'MID', isTop: true },
    { name: 'Adalberto Carrasquilla', position: 'MID', isTop: true },
    { name: 'Cecilio Waterman', position: 'FWD', isTop: true },
    { name: 'Alberto Quintero', position: 'FWD' },
    { name: 'Rolando Blackburn', position: 'FWD', isTop: true },
    { name: 'Ismael Díaz', position: 'FWD', isTop: true },
    { name: 'José Fajardo', position: 'FWD' },
    { name: 'Julio Motta', position: 'DEF' },
    { name: 'Roderick Miller', position: 'DEF' },
    { name: 'Harold Cummings', position: 'DEF', isTop: true },
    { name: 'Blas Pérez', position: 'FWD' },
    { name: 'Édgar Yoel', position: 'DEF' },
    { name: 'Michael Murillo', position: 'DEF' },
    { name: 'Jovani Welch', position: 'MID' },
  ]),
  Egypt: sq('EGY', [
    { name: 'Mohamed El-Shenawy', position: 'GK', isTop: true },
    { name: 'Mostafa Shobeir', position: 'GK' },
    { name: 'Ibrahim Adel', position: 'GK' },
    { name: 'Omar Kamal', position: 'DEF' },
    { name: 'Ahmed Hegazy', position: 'DEF', isTop: true },
    { name: 'Mahmoud Hamdi', position: 'DEF', isTop: true },
    { name: 'Omar Gaber', position: 'DEF', isTop: true },
    { name: 'Akram Tawfik', position: 'DEF' },
    { name: 'Mohamed Abdel-Moneim', position: 'DEF' },
    { name: 'Nasser Maher', position: 'MID' },
    { name: 'Tarek Hamed', position: 'MID', isTop: true },
    { name: 'Amr El-Solia', position: 'MID' },
    { name: 'Emam Ashour', position: 'MID', isTop: true },
    { name: 'Mohamed Elneny', position: 'MID', isTop: true },
    { name: 'Zizo', position: 'MID', isTop: true },
    { name: 'Mohamed Salah', position: 'FWD', isTop: true },
    { name: 'Trezeguet', position: 'FWD', isTop: true },
    { name: 'Ramadan Sobhi', position: 'FWD', isTop: true },
    { name: 'Omar Marmoush', position: 'FWD', isTop: true },
    { name: 'Mostafa Mohamed', position: 'FWD', isTop: true },
    { name: 'Kahraba', position: 'FWD' },
    { name: 'Ahmed Sayed Zizou', position: 'FWD' },
  ]),
  Algeria: sq('ALG', [
    { name: "Raïs M'Bolhi", position: 'GK', isTop: true },
    { name: 'Alexandre Oukidja', position: 'GK' },
    { name: 'Lucas Chevalier', position: 'GK' },
    { name: 'Mehdi Zeffane', position: 'DEF', isTop: true },
    { name: 'Ramy Bensebaïni', position: 'DEF', isTop: true },
    { name: 'Djamel Benlamri', position: 'DEF', isTop: true },
    { name: 'Aïssa Mandi', position: 'DEF', isTop: true },
    { name: 'Saïd Benrahma', position: 'MID', isTop: true },
    { name: 'Ismaël Bennacer', position: 'MID', isTop: true },
    { name: 'Ramiz Zerrouki', position: 'MID', isTop: true },
    { name: 'Sofiane Feghouli', position: 'MID' },
    { name: 'Adam Ounas', position: 'FWD', isTop: true },
    { name: 'Youcef Belaïli', position: 'FWD' },
    { name: 'Baghdad Bounedjah', position: 'FWD' },
    { name: 'Riyad Mahrez', position: 'FWD', isTop: true },
    { name: 'Yacine Brahimi', position: 'FWD', isTop: true },
    { name: 'Islam Slimani', position: 'FWD' },
    { name: 'Andy Delort', position: 'FWD' },
    { name: 'Farès Chaïbi', position: 'MID' },
    { name: 'Mohamed Amine Amoura', position: 'FWD', isTop: true },
    { name: 'Ilyes Houari', position: 'DEF' },
    { name: 'Houssem Aouar', position: 'MID' },
  ]),
  Scotland: sq('SCO', [
    { name: 'Craig Gordon', position: 'GK', isTop: true },
    { name: 'Liam Kelly', position: 'GK' },
    { name: 'Jon McLaughlin', position: 'GK' },
    { name: 'Aaron Hickey', position: 'DEF', isTop: true },
    { name: 'Anthony Ralston', position: 'DEF' },
    { name: 'Grant Hanley', position: 'DEF', isTop: true },
    { name: 'Scott McKenna', position: 'DEF', isTop: true },
    { name: 'Kieran Tierney', position: 'DEF', isTop: true },
    { name: 'Greg Taylor', position: 'DEF' },
    { name: 'Liam Cooper', position: 'DEF' },
    { name: 'John McGinn', position: 'MID', isTop: true },
    { name: 'Stuart Armstrong', position: 'MID', isTop: true },
    { name: 'Ryan Christie', position: 'MID', isTop: true },
    { name: 'Callum McGregor', position: 'MID', isTop: true },
    { name: 'Billy Gilmour', position: 'MID', isTop: true },
    { name: 'Scott McTominay', position: 'MID', isTop: true },
    { name: 'Che Adams', position: 'FWD', isTop: true },
    { name: 'Lyndon Dykes', position: 'FWD', isTop: true },
    { name: 'Ryan Fraser', position: 'FWD' },
    { name: 'Kevin Nisbet', position: 'FWD' },
    { name: 'Lawrence Shankland', position: 'FWD', isTop: true },
    { name: 'Jack Hendry', position: 'DEF' },
  ]),
  Paraguay: sq('PAR', [
    { name: 'Antony Silva', position: 'GK', isTop: true },
    { name: 'Alfredo Aguilar', position: 'GK' },
    { name: 'Rodrigo Muñoz', position: 'GK' },
    { name: 'Robert Rojas', position: 'DEF', isTop: true },
    { name: 'Junior Alonso', position: 'DEF', isTop: true },
    { name: 'Gustavo Gómez', position: 'DEF', isTop: true },
    { name: 'Fabián Balbuena', position: 'DEF', isTop: true },
    { name: 'Santiago Arzamendia', position: 'DEF', isTop: true },
    { name: 'Omar Alderete', position: 'DEF', isTop: true },
    { name: 'Mathías Villasanti', position: 'MID', isTop: true },
    { name: 'Andrés Cubas', position: 'MID', isTop: true },
    { name: 'Ángel Romero', position: 'FWD', isTop: true },
    { name: 'Óscar Romero', position: 'MID', isTop: true },
    { name: 'Alejandro Romero Gamarra', position: 'FWD' },
    { name: 'Braian Samudio', position: 'FWD' },
    { name: 'Carlos González', position: 'FWD' },
    { name: 'Julio Enciso', position: 'FWD', isTop: true },
    { name: 'Cecilio Domínguez', position: 'FWD' },
    { name: 'Abel Hernández', position: 'FWD' },
    { name: 'Reinaldo Rennella', position: 'FWD' },
    { name: 'Gabriel Ávalos', position: 'FWD' },
    { name: 'Miguel Almirón', position: 'MID', isTop: true },
  ]),
  Tunisia: sq('TUN', [
    { name: 'Aymen Dahmen', position: 'GK', isTop: true },
    { name: 'Bechir Ben Said', position: 'GK' },
    { name: 'Farouk Ben Mustapha', position: 'GK' },
    { name: 'Mohamed Drager', position: 'DEF', isTop: true },
    { name: 'Montassar Talbi', position: 'DEF', isTop: true },
    { name: 'Yassine Meriah', position: 'DEF', isTop: true },
    { name: 'Nader Ghandri', position: 'DEF', isTop: true },
    { name: 'Dylan Bronn', position: 'DEF', isTop: true },
    { name: 'Ali Maaloul', position: 'DEF', isTop: true },
    { name: 'Wajdi Kechrida', position: 'DEF' },
    { name: 'Anis Slimane', position: 'MID', isTop: true },
    { name: 'Ferjani Sassi', position: 'MID', isTop: true },
    { name: 'Ellyes Skhiri', position: 'MID', isTop: true },
    { name: 'Hannibal Mejbri', position: 'MID', isTop: true },
    { name: 'Mohamed Ali Ben Romdhane', position: 'MID' },
    { name: 'Wahbi Khazri', position: 'FWD', isTop: true },
    { name: 'Youssef Msakni', position: 'FWD' },
    { name: 'Seifeddine Jaziri', position: 'FWD' },
    { name: 'Issam Jebali', position: 'FWD', isTop: true },
    { name: 'Taha Yassine Khenissi', position: 'FWD' },
    { name: 'Anis Ben Slimane', position: 'MID' },
    { name: 'Naïm Sliti', position: 'FWD' },
  ]),
  'Ivory Coast': sq('CIV', [
    { name: 'Yahia Fofana', position: 'GK', isTop: true },
    { name: 'Badra Ali Sangaré', position: 'GK' },
    { name: 'Sylvain Gbohouo', position: 'GK' },
    { name: 'Serge Aurier', position: 'DEF', isTop: true },
    { name: 'Wilfried Singo', position: 'DEF', isTop: true },
    { name: 'Willy Boly', position: 'DEF', isTop: true },
    { name: 'Eric Bailly', position: 'DEF', isTop: true },
    { name: 'Odilon Kossounou', position: 'DEF', isTop: true },
    { name: 'Ghislain Konan', position: 'DEF' },
    { name: 'Cédric Bade', position: 'DEF' },
    { name: 'Jean-Michaël Seri', position: 'MID' },
    { name: 'Franck Kessié', position: 'MID', isTop: true },
    { name: 'Ibrahim Sangaré', position: 'MID', isTop: true },
    { name: 'Ismaël Traoré', position: 'MID' },
    { name: 'Seko Fofana', position: 'MID', isTop: true },
    { name: 'Nicolas Pépé', position: 'FWD', isTop: true },
    { name: 'Wilfried Zaha', position: 'FWD', isTop: true },
    { name: 'Simon Adingra', position: 'FWD', isTop: true },
    { name: 'Sébastien Haller', position: 'FWD', isTop: true },
    { name: 'Maxwel Cornet', position: 'FWD' },
    { name: 'Jonathan Kodjia', position: 'FWD' },
    { name: 'Christian Kouamé', position: 'FWD' },
  ]),
  Uzbekistan: sq('UZB', [
    { name: 'Abduvohid Nematov', position: 'GK', isTop: true },
    { name: 'Utkir Yusupov', position: 'GK' },
    { name: 'Botir Yusupov', position: 'DEF', isTop: true },
    { name: 'Dostonbek Khamdamov', position: 'DEF', isTop: true },
    { name: 'Alisher Djalilov', position: 'DEF', isTop: true },
    { name: 'Husan Abdullaev', position: 'DEF', isTop: true },
    { name: 'Khojiakbar Alijonov', position: 'DEF' },
    { name: 'Akbar Mamashayev', position: 'DEF' },
    { name: 'Jaloliddin Masharipov', position: 'MID', isTop: true },
    { name: 'Otabek Shukurov', position: 'MID', isTop: true },
    { name: 'Shamsiddin Shomurodov', position: 'MID', isTop: true },
    { name: 'Islom Tukhtakhujaev', position: 'MID', isTop: true },
    { name: 'Sanjar Kuvvatov', position: 'MID' },
    { name: 'Eldor Shomurodov', position: 'FWD', isTop: true },
    { name: 'Javokhir Sidiqov', position: 'FWD', isTop: true },
    { name: 'Abbosbek Fayzullaev', position: 'FWD', isTop: true },
    { name: 'Khurshid Mamatov', position: 'FWD' },
    { name: 'Temur Jalolov', position: 'FWD', isTop: true },
    { name: 'Dostonbek Khasanov', position: 'MID' },
    { name: 'Muzaffar Kasymov', position: 'MID' },
    { name: 'Bekzod Kholmatov', position: 'DEF' },
    { name: 'Mirjalol Qosimov', position: 'FWD' },
  ]),
  Qatar: sq('QAT', [
    { name: 'Meshaal Barsham', position: 'GK', isTop: true },
    { name: 'Yousef Hassan', position: 'GK' },
    { name: 'Saad Al-Sheeb', position: 'GK' },
    { name: 'Pedro Miguel', position: 'DEF', isTop: true },
    { name: 'Bassam Al-Rawi', position: 'DEF', isTop: true },
    { name: 'Tarek Salman', position: 'DEF' },
    { name: 'Boualem Khoukhi', position: 'DEF', isTop: true },
    { name: 'Musab Kheder', position: 'DEF' },
    { name: 'Homam Ahmed', position: 'DEF', isTop: true },
    { name: 'Karim Boudiaf', position: 'MID', isTop: true },
    { name: 'Abdulaziz Hatem', position: 'MID', isTop: true },
    { name: 'Mohammed Waad', position: 'MID' },
    { name: 'Ismaël Mohammad', position: 'MID' },
    { name: 'Assim Omer Madibo', position: 'MID', isTop: true },
    { name: 'Salem Al-Hajri', position: 'MID' },
    { name: 'Almoez Ali', position: 'FWD', isTop: true },
    { name: 'Akram Afif', position: 'FWD', isTop: true },
    { name: 'Hasan Al-Haydos', position: 'FWD', isTop: true },
    { name: 'Yousuf Abdurisag', position: 'FWD', isTop: true },
    { name: 'Naif Al Hadhrami', position: 'FWD' },
    { name: 'Sultan Al Brake', position: 'FWD' },
    { name: 'Ahmed Alaaeldin', position: 'FWD' },
  ]),
  'Saudi Arabia': sq('KSA', [
    { name: 'Mohammed Al-Owais', position: 'GK', isTop: true },
    { name: 'Fawaz Al-Qarni', position: 'GK' },
    { name: 'Mohammed Al-Yami', position: 'GK' },
    { name: 'Saud Abdulhamid', position: 'DEF', isTop: true },
    { name: 'Sultan Al-Ghannam', position: 'DEF', isTop: true },
    { name: 'Ali Al-Bulaihi', position: 'DEF', isTop: true },
    { name: 'Abdulelah Al-Amri', position: 'DEF', isTop: true },
    { name: 'Hassan Tambakti', position: 'DEF', isTop: true },
    { name: 'Mohammed Al-Burayk', position: 'DEF' },
    { name: 'Ahmed Sharahili', position: 'DEF' },
    { name: 'Abdulrahman Al-Aboud', position: 'MID', isTop: true },
    { name: 'Mohammed Kanno', position: 'MID', isTop: true },
    { name: 'Sami Al-Najei', position: 'MID', isTop: true },
    { name: 'Ali Al-Hassan', position: 'MID' },
    { name: 'Nasser Al-Dawsari', position: 'FWD', isTop: true },
    { name: 'Salem Al-Dawsari', position: 'FWD', isTop: true },
    { name: 'Saleh Al-Shehri', position: 'FWD', isTop: true },
    { name: 'Firas Al-Buraikan', position: 'FWD', isTop: true },
    { name: 'Khaled Al-Ghannam', position: 'FWD' },
    { name: 'Abdullah Al-Hamdan', position: 'FWD' },
    { name: 'Hattan Bahebri', position: 'FWD' },
    { name: 'Yasser Al-Shahrani', position: 'DEF' },
  ]),
  'South Africa': sq('RSA', [
    { name: 'Ronwen Williams', position: 'GK', isTop: true },
    { name: 'Veli Mothwa', position: 'GK' },
    { name: 'Bruce Bvuma', position: 'GK' },
    { name: 'Terrence Mashego', position: 'DEF', isTop: true },
    { name: 'Njabulo Ngcobo', position: 'DEF', isTop: true },
    { name: 'Rushine De Reuck', position: 'DEF', isTop: true },
    { name: 'Thibang Phete', position: 'DEF' },
    { name: 'Siyanda Xulu', position: 'DEF' },
    { name: 'Nkosinathi Sibisi', position: 'DEF', isTop: true },
    { name: 'Aubrey Modiba', position: 'DEF', isTop: true },
    { name: 'Mothobi Mvala', position: 'MID', isTop: true },
    { name: 'Ethan Cresswell', position: 'MID' },
    { name: 'Teboho Mokoena', position: 'MID', isTop: true },
    { name: 'Lyle Foster', position: 'FWD', isTop: true },
    { name: 'Percy Tau', position: 'FWD', isTop: true },
    { name: 'Themba Zwane', position: 'FWD', isTop: true },
    { name: 'Bongokuhle Hlongwane', position: 'FWD', isTop: true },
    { name: 'Fagrie Lakay', position: 'FWD' },
    { name: 'Bradley Grobler', position: 'FWD' },
    { name: 'Evidence Makgopa', position: 'FWD', isTop: true },
    { name: 'Nhlanhla Vilakazi', position: 'MID' },
    { name: 'Khuliso Mudau', position: 'DEF' },
  ]),

  // ── POT 4 ──────────────────────────────────────────────────────────────────
  Jordan: sq('JOR', [
    { name: 'Yazeed Abulaila', position: 'GK', isTop: true },
    { name: 'Ahmad Al-Rousan', position: 'GK' },
    { name: 'Musa Al-Taamari', position: 'FWD', isTop: true },
    { name: 'Yazan Al-Naimat', position: 'DEF', isTop: true },
    { name: 'Mahmoud Jaber', position: 'DEF', isTop: true },
    { name: "Baha' Faisal", position: 'DEF' },
    { name: 'Salem Al-Ajalin', position: 'DEF', isTop: true },
    { name: 'Montaser Al-Abadi', position: 'DEF' },
    { name: 'Saif Al-Mubaslat', position: 'DEF' },
    { name: 'Nour Mansour', position: 'MID', isTop: true },
    { name: 'Ehsan Haddad', position: 'MID', isTop: true },
    { name: 'Abdullah Nasib', position: 'MID', isTop: true },
    { name: 'Oday Dabbagh', position: 'FWD', isTop: true },
    { name: 'Yazan Al-Arab', position: 'FWD', isTop: true },
    { name: 'Ahmad Zyoud', position: 'FWD', isTop: true },
    { name: 'Mousa Al-Tamari', position: 'FWD', isTop: true },
    { name: 'Amro Hamdan', position: 'MID' },
    { name: 'Osama Rashid', position: 'MID' },
    { name: 'Ibrahim Alassi', position: 'MID' },
    { name: 'Ali Olwan', position: 'DEF' },
    { name: 'Rashed Al-Abdi', position: 'FWD' },
    { name: 'Mohammad Abu Zema', position: 'MID' },
  ]),
  'Cape Verde': sq('CPV', [
    { name: 'Vozinha', position: 'GK', isTop: true },
    { name: 'Elísio Mendes', position: 'GK' },
    { name: 'Dylan Tavares', position: 'DEF', isTop: true },
    { name: 'Júnior Morais', position: 'DEF', isTop: true },
    { name: 'Steven Fortes', position: 'DEF', isTop: true },
    { name: 'Roberto Lopes', position: 'DEF', isTop: true },
    { name: 'Stopira', position: 'DEF', isTop: true },
    { name: 'Diney', position: 'DEF' },
    { name: 'Jamiro Monteiro', position: 'MID', isTop: true },
    { name: 'Kévin Pina', position: 'MID', isTop: true },
    { name: 'Garry Rodrigues', position: 'FWD', isTop: true },
    { name: 'Willy Semedo', position: 'FWD' },
    { name: 'Djaniny', position: 'FWD', isTop: true },
    { name: 'Helidon Ramos', position: 'MID' },
    { name: 'Julio Tavares', position: 'FWD', isTop: true },
    { name: 'Ryan Mendes', position: 'FWD' },
    { name: 'Lúcio Antunes', position: 'MID' },
    { name: 'Kenny Rocha', position: 'MID' },
    { name: 'Bryan Tavares', position: 'MID' },
    { name: 'Marco Soares', position: 'DEF' },
    { name: 'Jovane Cabral', position: 'FWD', isTop: true },
    { name: 'Lisandro Semedo', position: 'DEF' },
  ]),
  Ghana: sq('GHA', [
    { name: 'Lawrence Ati Zigi', position: 'GK', isTop: true },
    { name: 'Jojo Wollacott', position: 'GK' },
    { name: 'Abdul Manaf Nurudeen', position: 'GK' },
    { name: 'Tariq Lamptey', position: 'DEF', isTop: true },
    { name: 'Andy Yiadom', position: 'DEF', isTop: true },
    { name: 'Alexander Djiku', position: 'DEF', isTop: true },
    { name: 'Daniel Amartey', position: 'DEF', isTop: true },
    { name: 'Abdul Baba Rahman', position: 'DEF', isTop: true },
    { name: 'Gideon Mensah', position: 'DEF' },
    { name: 'Alidu Seidu', position: 'DEF' },
    { name: 'Thomas Partey', position: 'MID', isTop: true },
    { name: 'Iddrisu Baba', position: 'MID' },
    { name: 'Elisha Owusu', position: 'MID' },
    { name: 'Jordan Ayew', position: 'FWD', isTop: true },
    { name: 'André Ayew', position: 'FWD', isTop: true },
    { name: 'Osman Bukari', position: 'FWD' },
    { name: 'Antoine Semenyo', position: 'FWD', isTop: true },
    { name: 'Mohammed Kudus', position: 'FWD', isTop: true },
    { name: 'Inaki Williams', position: 'FWD', isTop: true },
    { name: 'Felix Afena-Gyan', position: 'FWD' },
    { name: 'Daniel-Kofi Kyereh', position: 'MID' },
    { name: 'Kamaldeen Sulemana', position: 'FWD', isTop: true },
  ]),
  'Curaçao': sq('CUW', [
    { name: 'Eloy Room', position: 'GK', isTop: true },
    { name: 'Gianluca Nijholt', position: 'GK' },
    { name: 'Jurien Gaari', position: 'DEF', isTop: true },
    { name: 'Cuco Martina', position: 'DEF', isTop: true },
    { name: 'Rangelo Janga', position: 'FWD', isTop: true },
    { name: 'Leandro Bacuna', position: 'MID', isTop: true },
    { name: 'Jafar Arias', position: 'MID', isTop: true },
    { name: 'Sheraldo Becker', position: 'FWD', isTop: true },
    { name: 'Darryl Lachman', position: 'DEF', isTop: true },
    { name: 'Etienne Reijnen', position: 'DEF', isTop: true },
    { name: 'Jose Nahar', position: 'MID', isTop: true },
    { name: 'Vurnon Anita', position: 'MID' },
    { name: 'Geovanni', position: 'MID' },
    { name: 'Quentin Thureau', position: 'MID' },
    { name: 'Gevaro Nepomuceno', position: 'FWD' },
    { name: 'Charlison Benschop', position: 'FWD' },
    { name: 'Rignald Cicilia', position: 'FWD' },
    { name: 'Fernando Aristeguieta', position: 'FWD' },
    { name: 'Timothy Tillman', position: 'MID' },
    { name: 'Falvio Aponte', position: 'FWD' },
    { name: 'Genero Zeefuik', position: 'DEF' },
    { name: 'Chedric Bazoer', position: 'MID' },
  ]),
  Haiti: sq('HAI', [
    { name: 'Johny Placide', position: 'GK', isTop: true },
    { name: 'Steeven Saba', position: 'GK' },
    { name: 'Mechack Jerome', position: 'DEF', isTop: true },
    { name: 'Samuel Camille', position: 'DEF', isTop: true },
    { name: 'Wildrik McDonald', position: 'DEF', isTop: true },
    { name: 'Nenel Jolicoeur', position: 'DEF' },
    { name: 'Nicky Hernandez', position: 'DEF', isTop: true },
    { name: 'Olivier Verela', position: 'DEF', isTop: true },
    { name: 'Kervens Belfort', position: 'MID', isTop: true },
    { name: 'Carlens Arcus', position: 'MID', isTop: true },
    { name: 'Benoit Gustave', position: 'MID', isTop: true },
    { name: 'Carlo Dorsainvil', position: 'MID', isTop: true },
    { name: 'Chery Jeff Louis', position: 'MID' },
    { name: 'James Léandre', position: 'MID' },
    { name: 'Duckens Nazon', position: 'FWD', isTop: true },
    { name: 'Kevin Lafrance', position: 'FWD', isTop: true },
    { name: 'Frantzdy Pierrot', position: 'FWD', isTop: true },
    { name: 'Derrick Etienne', position: 'FWD', isTop: true },
    { name: 'Dorian Duclair', position: 'FWD' },
    { name: 'Herve Bazile', position: 'FWD' },
    { name: 'Gustave Cadet', position: 'FWD' },
    { name: 'Nazon Duckens', position: 'FWD' },
  ]),
  'New Zealand': sq('NZL', [
    { name: 'Stefan Marinovic', position: 'GK', isTop: true },
    { name: 'Oliver Sail', position: 'GK' },
    { name: 'Michael Boxall', position: 'DEF', isTop: true },
    { name: 'Winston Reid', position: 'DEF', isTop: true },
    { name: 'Tommy Smith', position: 'DEF', isTop: true },
    { name: 'Liberato Cacace', position: 'DEF', isTop: true },
    { name: 'Tim Payne', position: 'DEF' },
    { name: 'Bill Tuiloma', position: 'DEF', isTop: true },
    { name: 'Elijah Just', position: 'MID', isTop: true },
    { name: 'Joe Bell', position: 'MID', isTop: true },
    { name: 'Marko Stamenic', position: 'MID', isTop: true },
    { name: 'Callum McCowatt', position: 'MID', isTop: true },
    { name: 'Clayton Lewis', position: 'MID', isTop: true },
    { name: 'Ryan Thomas', position: 'MID' },
    { name: 'Chris Wood', position: 'FWD', isTop: true },
    { name: 'Kosta Barbarouses', position: 'FWD', isTop: true },
    { name: 'Sarpreet Singh', position: 'FWD', isTop: true },
    { name: 'Matt Garbett', position: 'MID' },
    { name: 'Hamish Watson', position: 'DEF' },
    { name: 'Declan Wynne', position: 'DEF' },
    { name: 'Ben Waine', position: 'FWD' },
    { name: 'Oli Sail', position: 'GK' },
  ]),
  'Bosnia & Herzegovina': sq('BIH', [
    { name: 'Kenan Pirić', position: 'GK', isTop: true },
    { name: 'Ibrahim Šehić', position: 'GK' },
    { name: 'Sead Kolašinac', position: 'DEF', isTop: true },
    { name: 'Ervin Zukanović', position: 'DEF', isTop: true },
    { name: 'Anel Ahmedhodžić', position: 'DEF', isTop: true },
    { name: 'Mensur Mujdža', position: 'DEF' },
    { name: 'Samir Memišević', position: 'DEF', isTop: true },
    { name: 'Petar Stojanović', position: 'DEF', isTop: true },
    { name: 'Miralem Pjanić', position: 'MID', isTop: true },
    { name: 'Muhamed Bešić', position: 'MID', isTop: true },
    { name: 'Zlatan Gojak', position: 'MID', isTop: true },
    { name: 'Haris Hajradinović', position: 'MID', isTop: true },
    { name: 'Dario Kolobarić', position: 'MID' },
    { name: 'Ivan Šunjić', position: 'MID' },
    { name: 'Haris Duljevic', position: 'MID' },
    { name: 'Edin Džeko', position: 'FWD', isTop: true },
    { name: 'Armin Hodžić', position: 'FWD', isTop: true },
    { name: 'Edin Višća', position: 'FWD', isTop: true },
    { name: 'Nemanja Bilbija', position: 'FWD' },
    { name: 'Benjamin Verbič', position: 'FWD' },
    { name: 'Ognjen Gunjić', position: 'GK' },
    { name: 'Adnan Džeko', position: 'FWD' },
  ]),
  Sweden: sq('SWE', [
    { name: 'Robin Olsen', position: 'GK', isTop: true },
    { name: 'Karl-Johan Johnsson', position: 'GK' },
    { name: 'Emil Krafth', position: 'DEF', isTop: true },
    { name: 'Mikael Lustig', position: 'DEF' },
    { name: 'Marcus Danielson', position: 'DEF', isTop: true },
    { name: 'Carl Starfelt', position: 'DEF', isTop: true },
    { name: 'Ludwig Augustinsson', position: 'DEF', isTop: true },
    { name: 'Filip Helander', position: 'DEF', isTop: true },
    { name: 'Victor Lindelöf', position: 'DEF', isTop: true },
    { name: 'Albin Ekdal', position: 'MID' },
    { name: 'Kristoffer Olsson', position: 'MID', isTop: true },
    { name: 'Sebastian Larsson', position: 'MID' },
    { name: 'Emil Forsberg', position: 'MID', isTop: true },
    { name: 'Dejan Kulusevski', position: 'FWD', isTop: true },
    { name: 'Alexander Isak', position: 'FWD', isTop: true },
    { name: 'Robin Quaison', position: 'FWD' },
    { name: 'Jordan Larsson', position: 'FWD' },
    { name: 'Marcus Berg', position: 'FWD' },
    { name: 'Anthony Elanga', position: 'FWD', isTop: true },
    { name: 'Mattias Svanberg', position: 'MID', isTop: true },
    { name: 'Samuel Chukwueze', position: 'FWD' },
    { name: 'Williot Swedberg', position: 'FWD', isTop: true },
  ]),
  Ukraine: sq('UKR', [
    { name: 'Andriy Pyatov', position: 'GK' },
    { name: 'Georgiy Bushchan', position: 'GK', isTop: true },
    { name: 'Anatoliy Trubin', position: 'GK', isTop: true },
    { name: 'Oleksandr Zinchenko', position: 'DEF', isTop: true },
    { name: 'Serhiy Kryvtsov', position: 'DEF' },
    { name: 'Mykola Matviyenko', position: 'DEF', isTop: true },
    { name: 'Illia Zabarnyi', position: 'DEF', isTop: true },
    { name: 'Vitaliy Mykolenko', position: 'DEF', isTop: true },
    { name: 'Oleksandr Tymchyk', position: 'DEF', isTop: true },
    { name: 'Mykhailo Mudryk', position: 'FWD', isTop: true },
    { name: 'Ruslan Malinovskyi', position: 'MID', isTop: true },
    { name: 'Taras Stepanenko', position: 'MID', isTop: true },
    { name: 'Mykhailo Tsygankov', position: 'MID' },
    { name: 'Viktor Tsygankov', position: 'MID', isTop: true },
    { name: 'Heorhiy Sudakov', position: 'MID', isTop: true },
    { name: 'Artem Dovbyk', position: 'FWD', isTop: true },
    { name: 'Roman Yaremchuk', position: 'FWD', isTop: true },
    { name: 'Andriy Yarmolenko', position: 'FWD' },
    { name: 'Oleksandr Zubkov', position: 'FWD' },
    { name: 'Volodymyr Brazhko', position: 'MID' },
    { name: 'Danylo Sikan', position: 'FWD' },
    { name: 'Dmytro Riznyk', position: 'GK' },
  ]),
  Greece: sq('GRE', [
    { name: 'Odysseas Vlachodimos', position: 'GK', isTop: true },
    { name: 'Kostas Tzolakis', position: 'GK' },
    { name: 'Konstantinos Mavropanos', position: 'DEF', isTop: true },
    { name: 'Giorgos Vagiannidis', position: 'DEF', isTop: true },
    { name: 'Panagiotis Retsos', position: 'DEF', isTop: true },
    { name: 'Konstantinos Koulierakis', position: 'DEF', isTop: true },
    { name: 'Sotiris Alexandropoulos', position: 'MID', isTop: true },
    { name: 'Kostas Fortounis', position: 'MID', isTop: true },
    { name: 'Tasos Bakasetas', position: 'MID', isTop: true },
    { name: 'Petros Mantalos', position: 'MID' },
    { name: 'Andreas Bouchalakis', position: 'MID' },
    { name: 'Manolis Siopis', position: 'MID', isTop: true },
    { name: 'Dimitris Pelkas', position: 'MID', isTop: true },
    { name: 'Christos Tzolis', position: 'FWD', isTop: true },
    { name: 'Vangelis Pavlidis', position: 'FWD', isTop: true },
    { name: 'Giorgos Giakoumakis', position: 'FWD', isTop: true },
    { name: 'Lazaros Rota', position: 'FWD' },
    { name: 'Nikos Katsaros', position: 'FWD' },
    { name: 'Giorgos Masouras', position: 'FWD' },
    { name: 'Dimitris Limnios', position: 'FWD' },
    { name: 'Anastasios Douvikas', position: 'FWD' },
    { name: 'Kwame Osei-Bonsu', position: 'MID' },
  ]),
  'DR Congo': sq('COD', [
    { name: 'Ley Matampi', position: 'GK', isTop: true },
    { name: 'Joël Kiassumbua', position: 'GK' },
    { name: 'Chancel Mbemba', position: 'DEF', isTop: true },
    { name: 'Arthur Masuaku', position: 'DEF', isTop: true },
    { name: 'Gabriel Zakuani', position: 'DEF' },
    { name: 'Elia Meschack', position: 'DEF', isTop: true },
    { name: 'Youssouf Mulumbu', position: 'MID', isTop: true },
    { name: 'Neeskens Kebano', position: 'MID', isTop: true },
    { name: 'Paul-José Mpoku', position: 'MID', isTop: true },
    { name: 'Merveille Bope Bokadi', position: 'MID', isTop: true },
    { name: 'Samuel Bastien', position: 'MID', isTop: true },
    { name: 'Yannick Bolasie', position: 'FWD', isTop: true },
    { name: 'Cédric Bakambu', position: 'FWD', isTop: true },
    { name: 'Dieumerci Mbokani', position: 'FWD' },
    { name: 'Benik Afobe', position: 'FWD', isTop: true },
    { name: 'Silas Wamangituka', position: 'FWD', isTop: true },
    { name: 'Nathan Nzola', position: 'FWD', isTop: true },
    { name: 'Theo Bongonda', position: 'FWD' },
    { name: 'Ben Malango', position: 'FWD' },
    { name: 'Juvhel Tsoumou', position: 'FWD' },
    { name: 'Djuma Shabani', position: 'MID' },
    { name: 'Emmanuel Leka Mbokani', position: 'FWD' },
  ]),
  Iraq: sq('IRQ', [
    { name: 'Jalal Hassan', position: 'GK', isTop: true },
    { name: 'Mohammed Hameed', position: 'GK' },
    { name: 'Ali Adnan', position: 'DEF', isTop: true },
    { name: 'Saad Abdul Amir', position: 'DEF', isTop: true },
    { name: 'Amjad Attwan', position: 'DEF', isTop: true },
    { name: 'Mustafa Nadhim', position: 'DEF', isTop: true },
    { name: 'Zaid Tahsin', position: 'DEF', isTop: true },
    { name: 'Karrar Mohammed', position: 'MID', isTop: true },
    { name: 'Mohammed Dawood', position: 'MID', isTop: true },
    { name: 'Ahmed Yasin', position: 'MID', isTop: true },
    { name: 'Hasan Abdulkareem', position: 'MID', isTop: true },
    { name: 'Bassim Abbas', position: 'MID' },
    { name: 'Ameen Al-Danbajah', position: 'MID' },
    { name: 'Mahdi Kamil', position: 'MID' },
    { name: 'Ali Al-Hamadi', position: 'FWD', isTop: true },
    { name: 'Saman Sadiq', position: 'FWD', isTop: true },
    { name: 'Aymen Hussein', position: 'FWD', isTop: true },
    { name: 'Alaa Abdul Zahra', position: 'FWD', isTop: true },
    { name: 'Mohanad Ali', position: 'FWD', isTop: true },
    { name: 'Dana Jalal', position: 'FWD' },
    { name: 'Ahmad Nabil', position: 'FWD' },
    { name: 'Ahmad Ibrahim', position: 'GK' },
  ]),
};

export function getSquadForTeam(teamName) {
  return WC_SQUADS[teamName] || null;
}
